### ISSUE TITLE
ERROR  Browser.runtime.onConnect.addListener not implemented.

### ISSUE THREAD

**Issue by thomasf1** [serversideup/webext-bridge#95]
### Version

6.0.1

### Current Behavior

WXT seems to run into an issue when adding webext-bridge to the background script. It does not start the dev server with: ERROR  Browser.runtime.onConnect.addListener not implemented.

### Expected Behavior

For WXT dev server to start

### Steps To Reproduce

Adding the following to the background script:
```javascript
import { onMessage, sendMessage, allowWindowMessaging } from "webext-bridge/background"
```
(compiles ok)
and then using it (onmessage) or 
```javascript
allowWindowMessaging('mynamespace')
(or)
onMessage("test1", (params) => {
  console.log('test1 background', params);
  return 'hey from test1 background'; //loadUserPreferences(sync);
});
```

Runs into the following:
```javascript
✖ Command failed after 359 ms                                                                                                          02:52:53

 ERROR  Browser.runtime.onConnect.addListener not implemented.                                                                          02:52:53

Mock the function yourself using your testing framework, or submit a PR with an in-memory implementation.


  Mock the function yourself using your testing framework, or submit a PR with an in-memory implementation.
  at Object.addListener (node_modules/.pnpm/@webext-core+fake-browser@1.3.1/node_modules/@webext-core/fake-browser/lib/index.js:4387:15)
  at node_modules/.pnpm/webext-bridge@6.0.1/node_modules/webext-bridge/dist/background.js:154:27
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
  at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
  at ViteNodeRunner.interopedImport (node_modules/.pnpm/vite-node@2.1.4_@types+node@22.8.2/node_modules/vite-node/dist/client.mjs:421:28)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@2.1.4_@types+node@22.8.2/node_modules/vite-node/dist/client.mjs:280:24)
  at ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@2.1.4_@types+node@22.8.2/node_modules/vite-node/dist/client.mjs:206:14)
  at ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@2.1.4_@types+node@22.8.2/node_modules/vite-node/dist/client.mjs:259:12)
  at entrypoints/background.js:3:31
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@2.1.4_@types+node@22.8.2/node_modules/vite-node/dist/client.mjs:399:5)
```

 ELIFECYCLE  Command failed with exit code 1.

### Anything else?

Here the installed packages:

@wxt-dev/auto-icons 1.0.2
typescript 5.6.3
webext-bridge 6.0.1
wxt 0.19.13

Not quite sure how to approach this. Adding the same to the window script (with the /window import) seems fine

**Comment by thomasf1** [comment]
This might be more about wxt than it is about webext-bridge actually...

**Comment by thomasf1** [comment]
What baffles me though is that as it´s mentioned in the WXT docs, I would assume a lot of people would use the combination...

**Comment by thomasf1** [comment]
The solution was to move `allowWindowMessaging('xxx');` into the main function, I just tried some example code without accounting for that.
